//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1_DynamicForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormPage
    {
        public int Id { get; set; }
        public int PageNumber { get; set; }
        public string HtmlCode { get; set; }
        public int WholeFormId { get; set; }
    
        public virtual WholeForm WholeForm { get; set; }
    }
}
