//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1_DynamicForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormSubmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FormSubmission()
        {
            this.SubmissionWholes = new HashSet<SubmissionWhole>();
        }
    
        public int Id { get; set; }
        public string ApprovalStatus { get; set; }
        public int WholeFormId { get; set; }
    
        public virtual WholeForm WholeForm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionWhole> SubmissionWholes { get; set; }
    }
}
