//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1_DynamicForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubmissionWhole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubmissionWhole()
        {
            this.AccountWorkflows = new HashSet<AccountWorkflow>();
            this.SubmissionParts = new HashSet<SubmissionPart>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> DateModified { get; set; }
        public string Finished { get; set; }
        public int AccountId { get; set; }
        public int FormSubmissionId { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountWorkflow> AccountWorkflows { get; set; }
        public virtual FormSubmission FormSubmission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubmissionPart> SubmissionParts { get; set; }
    }
}
