//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Team1_DynamicForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WholeForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WholeForm()
        {
            this.FormPages = new HashSet<FormPage>();
            this.FormSubmissions = new HashSet<FormSubmission>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AccountId { get; set; }
        public int WorkFlowId { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormPage> FormPages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormSubmission> FormSubmissions { get; set; }
        public virtual WorkFlow WorkFlow { get; set; }
    }
}
